version: "3"
services:
  api-gateway:
    build: "./apigateway"
    depends_on:
      - listings-service
      - users-service
    environment:
      - LISTINGS_SERVICE_URI=http://listings-service:7100
      - USERS_SERVICE_URI=http://users-service:7101
    ports:
      - "7000:7000"
    volumes:
      - ./apigateway:/opt/app

  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=mysql://root:password@listings-service-db/db?charset=utf-8
    volumes:
      - ./listings-service:/opt/app
    ports:
      - 7100:7100

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:latest
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=utf-8
    volumes:
      - ./users-service:/opt/app
    ports:
      - 7101:7101
  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:latest
    ports:
      - 0.0.0.0:7201:3306
